//políticas de privacidades
module.exports = ({ env }) => [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            "io.cnpgc.embrapa.br",
            "market-assets.strapi.io",
            `cloud.agro.rocks:${process.env.MINIO_PORT0}`,
            `cloud.agro.rocks:${process.env.STRAPI_PORT}`,
            "cloud.agro.rocks",
            "res.cloudinary.com",
          ],
          "frame-src": [
            "'self'",
            "youtube.com",
            "www.youtube.com",
            "vimeo.com",
            "*.vimeo.com",
            "facebook.com",
            "www.facebook.com",
            "io.cnpgc.embrapa.br",
            "cloud.agro.rocks",
            "market-assets.strapi.io",
            `cloud.agro.rocks:${process.env.MINIO_PORT0}`,
            `cloud.agro.rocks:${process.env.STRAPI_PORT}`,
          ],
          "connect-src": ["'self'", "https:", "blob:", "*.strapi.io", "data:"],
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            "localhost:1337",
            `cloud.agro.rocks:${process.env.MINIO_PORT0}`,
            "dl.airtable.com",
            "cloud.agro.rocks",
            "market-assets.strapi.io",
            `cloud.agro.rocks:${process.env.STRAPI_PORT}`,
            "res.cloudinary.com",
          ],
          "style-src": ["'self'", "'unsafe-inline'"],
          "script-src": ["'self'", "cdn.jsdelivr.net", "blob:", "https:"],
          "font-src": ["'self'"],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  // {
  //   name: "strapi::cors",
  //   config: {
  //     origin: ["http://cloud.agro.rocks", "http://cloud.agro.rocks:49190", "http://localhost:1337"],
  //     methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"],
  //     headers: ["Content-Type", "Authorization", "Origin", "Accept"],
  //     keepHeaderOnError: true,
  //   },
  // },
  "strapi::cors",

  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
  { resolve: "./src/middlewares/redirect" },
];
